### PR TITLE
implemented MessageResponse for Vec<T>

### PR DESCRIPTION
**Pull request by BartWillems**
Signed-off-by: Bart Willems

## PR Type

Feature

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

This PR allows responding with std Vec for message responses.

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Review by ibraheemdev — COMMENTED** [review]
:+1:

**Comment by robjtede** [comment]
A quick test case would be great.

**Comment by BartWillems** [comment]
I've added 

> A quick test case would be great.

I've added some tests in the tests/test_messages.rs file

**Review by otavio — APPROVED** [review]

**Review by otavio — APPROVED** [review]

**Comment by BartWillems** [comment]
It seems that all the test files with `#![cfg(feature = "derive")]` at the top actually never get run.
They should be renamed to `feature = "macros"`

**Comment by robjtede** [comment]
> If you want, I can add this change in this PR, they all still seem to pass.

Nice spot, please do. CI tests are run with --all-features so that's why this wasn't caught or really a problem before.

**Review by popzxc — APPROVED** [review]

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
nice work and tests @BartWillems, thanks 👍🏻

**Pull request merged**
