### PR TITLE
Use `once_cell` over `lazy_static`

### PR DESCRIPTION
**Pull request by JohnTitor**
Use `once_cell` over `lazy_static` to acquire macro-free. This adds additional dependency but I'm fine with that since the community seems to prefer `once_cell` nowadays.

### CODE REVIEW

**Comment by cetra3** [comment]
I don't think we support actix in `no-std` do we? Otherwise no issues from me.

**Comment by JohnTitor** [comment]
> I don't think we support actix in no-std do we?

Yeah but I think `once_cell` is more flexible than `lazy_static` and maybe in std in the future so I would like to use and test on actix project.

If someone has any concerns (e.g. dependency addiction), feel free to point out.

**Comment by Jonathas-Conceicao** [comment]
I personally prefer once_cell over lazy_static and I have been moving my  projects to it. I'm fine with moving actix to it too.

**Comment by JohnTitor** [comment]
Okay, seems there is no concern, I'll merge this. Thanks all!

**Pull request merged**
