### PR TITLE
Add address to SyncContext

### PR DESCRIPTION
**Pull request by mmacedoeu**
On scenario where you want to do "recursive" calls this may help

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add test

**Comment by mmacedoeu** [comment]
test included

**Comment by fafhrd91** [comment]
@mmacedoeu do you still want to push this change to master?

**Comment by mmacedoeu** [comment]
Yes, I do

**Comment by fafhrd91** [comment]
please, update pr to master. I am planing to make new release soon

**Comment by mmacedoeu** [comment]
Closing this for new pull https://github.com/actix/actix/pull/341

**Pull request closed without merging**
