### PR TITLE
Implement Clone for WeakRecipient

### PR DESCRIPTION
**Pull request by geo-ant**
## PR Type
Feature

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated. (_rustdoc automatically shows the Clone trait implementation_)
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview
* `WeakRecipients`, like strong `Recipients` can now be cloned.
* `Recipient` now offers a `downgrade` method to obtain a `WeakRecipient`, similar to `Addr` and `WeakAddr`
* `WeakRecipient` can be converted from a `Recipient` via the `From` trait.

Potentially breaking changes:
* The `Sender` trait now requires a `downgrade` method. This affects code that implements its own `Sender` traits. However, this is not what many users would do.

Non-Breaking Changes:
* `WeakSender` is now public instead of crate-public. This did not use to be required, but the `downgrade` method on the publich `Sender` trait forces this.

## Issue
Closes [#518](https://github.com/actix/actix/issues/518)

### CODE REVIEW

**Comment by geo-ant** [comment]
Hey, can someone help on why the 1.46.0 pipelines are failing? I can't reproduce the failure locally on my linux box with the 1.46.0 toolchain. What I am seeing is:
```
   Compiling parking_lot_core v0.9.1
    Checking socket2 v0.4.4
    Checking mio v0.8.0
error[E0658]: use of unstable library feature 'renamed_spin_loop'
Error:  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.1/src/spinwait.rs:9:5
  |
9 | use core::hint::spin_loop;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error[E0658]: use of unstable library feature 'renamed_spin_loop'
Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.1/src/spinwait.rs:16:9
   |
16 |         spin_loop()
   |         ^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
```
which indicates a problem in the parking_lot_core crate, but as I said, I cannot reproduce this on my machine.

**Comment by robjtede** [comment]
It's almost certainly due to Tokio 1.17.0 bumping its MSRV to 1.49.

**Comment by robjtede** [comment]
I've bumped our MSRV to 1.49 here too.

**Comment by geo-ant** [comment]
> I've bumped our MSRV to 1.49 here too.

@robjtede thank you.

**Pull request merged**
