### PR TITLE
Make SendError Fail when possible.

### PR DESCRIPTION
**Pull request by ethanpailes**
The first step in resolving actix/actix-web#528.

I think there will need to be an actix release between when this PR gets merged and when the other patch goes into actix-web.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Thanks for PR, is this the whole content of PR you'd like to make or are there will be more changes?

**Comment by ethanpailes** [comment]
This is the whole content of the changes I'd like to make to actix. There are more changes that should go into actix-web, but they would not compile until SendError is Fail in actix itself, so they will have to wait until actix gets a new release and actix-web bumps it's actix version.

**Comment by fafhrd91** [comment]
@DoumanAsh could you add changes.md entry

**Comment by fafhrd91** [comment]
Thanks

**Pull request merged**
