### PR TITLE
chore: Update hashbrown to 0.5

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Closes: #264

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add entry to changes,md

**Comment by ignatenkobrain** [comment]
@fafhrd91 sure, one moment.

**Comment by ignatenkobrain** [comment]
@fafhrd91 done!

**Comment by JohnTitor** [comment]
Looks good to me but the branch is out-of-date.

**Comment by neoeinstein** [comment]
Note, in rustc 1.36, the `std::collections::HashMap` is hashbrown but with the default `SipHash` instead of `FxHash`. We could potentially just use the one in `std` and use `FxHash` as the hasher (or one of our own choosing) where appropriate. Bringing the hasher implementation internal to this crate could then reduce out the additional dependency.

**Comment by JohnTitor** [comment]
Reducing dependencies is good. What about the above comment? @fafhrd91

**Comment by fafhrd91** [comment]
I think this is good idea

**Comment by robjtede** [comment]
probably needs a rebase now the appveyor tests are fixed

**Comment by JohnTitor** [comment]
`hashbrown` has been deleted in #277. If updating `derive_more` is still reasonable, we should drop `hashbrown` from here.

**Comment by leizzer** [comment]
I would like to push this branch to an end. @ignatenkobrain could you update the PR and take @JohnTitor's advice?

**Pull request closed without merging**
