### PR TITLE
Notify the io::InnerWriter's task if necessary

### PR DESCRIPTION
**Pull request by habnabit**
>Unless the task is notified, the buffer isn't always flushed out after
every write. The actor's poll method would return NotReady when the
buffer empties without setting up a way to be notified when the buffer
was written to again.

### CODE REVIEW

**Comment by alanhoff** [comment]
This fixes the problem with #84, not sure why tests are failing on AppVeyor :/

**Comment by DoumanAsh** [comment]
Well tests are passing on my machine.

@fafhrd91 should we merge it?

**Comment by fafhrd91** [comment]
Ok

**Comment by habnabit** [comment]
I'm not sure what, if anything, would be useful for me to do here. It seems like CI is broken in some way?

I suppose adding a functional test or two would be useful here. I'm not sure how to unit test task notification.

**Comment by DoumanAsh** [comment]
@fafhrd91 Since nightly is currently broken, can you merge it without Travis check? It seems unnecessary to wait for it to get fixed

**Comment by fafhrd91** [comment]
Done

**Comment by fafhrd91** [comment]
@DoumanAsh you have permission to force push. Don’t overuse it :)

**Pull request merged**
