### PR TITLE
add ActorTryFuture{Ext} traits

### LINKED ISSUE #314: `TryFutureExt` functions for `ActorFuture`
The `TryFutureExt` extension trait offers functions like `and_then` and `map_err` for futures that return `Result` types. It would be great to have these functions available on `ActorFuture` as well.

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type

Feature

## PR Checklist
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview
Add `ActorTryFuture` and `ActorTryFutureExt` trait. Supports minimal combinators in the form of `map_ok`, `map_err` and `and_then`. 

Closes #314

### CODE REVIEW

**Comment by alexlapa** [comment]
Looking forward to this change.

Other extremely useful combinators would be `and_then` and `try_join_all`. I guess that it would make sense if they would be implemented in this PR.

Here is `try_join_all` implementation that i use: https://gist.github.com/alexlapa/70d4b179267169ecd86d4f896cd0dc6b, i believe it can be copy-pasted with some minor changes.

And i can also implement `and_then` in this PR / other PR / provide gist if that makes sense to you.

**Comment by robjtede** [comment]
@alexlapa Looks good! Yeah, please feel free to fork this branch and submit a superceeding PR. I'm unlikely to have bandwidth for this task for a while.

**Comment by fakeshadow** [comment]
This PR is ready. Other combinators can be separate PR.

**Review by robjtede — COMMENTED** [review]
LGTM

**Pull request merged**
