### PR TITLE
Remove the Unpin requirement on Response::fut()

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
# PR Type

This is a *Feature* -  it allows users to write code that they previously couldn't due to an overly strict `where` clause.

## PR Checklist
Check your PR fulfills the following:

- [X] Tests for the changes have been added / updated.
- [X] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [X] Format code with the latest stable rustfmt

## Overview

This PR removes a the `Unpin` requirement from the `Response::fut()` constructor's `where` clause, allowing a `Response` to be constructed using an `async` block or result of an `async` function. 

Previously, a `Response` could only be constructed via combinators (`futures::FutureExt` and friends) and using an `async` block would result in a type error.

This should be fully backwards compatible because: 

1. Any type that is `T: Future + Unpin + 'static` is also `T: Future + 'static`
2. The user can't directly access the `ResponseTypeItem::Fut` variant. So they won't know it's changed from `Box<dyn Future>` to `Pin<Box<dyn Future>>`

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
Is this large enough to warrant a change log entry?

**Comment by JohnTitor** [comment]
> Is this large enough to warrant a change log entry?

I'd love to see an entry for this :)

**Review by JohnTitor — APPROVED** [review]
I think this is reasonable.

**Comment by Michael-F-Bryan** [comment]
> I'd love to see an entry for this :)

Done.

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
