### PR TITLE
fix pop wrong item when cacel in handle

### PR DESCRIPTION
**Pull request by woodgear**
when you use cancel_future in handle it will sub the items len so the items.pop() will pop prevent item.
you could use this demo to see the different
or maybe i should not use self notify like this
PS: I do not fully understand actix's logic. so i just add patch fix that
~~~
// [dependencies]
// time = "0.1.39"
// actix = "0.4.0"
extern crate actix;
extern crate time;
use actix::prelude::*;
use actix::prelude::actix::SpawnHandle;
use std::time::Duration;
use std::thread::sleep;
use std::thread;

#[derive(Debug)]
enum Event {
    Update(String),
    Notify,
}
impl ResponseType for Event
{
    type Item = ();
    type Error = ();
}

struct ActorDemo {
    data:Option<String>,
    notify_handle: Option<SpawnHandle>
}

impl Actor for ActorDemo {
    type Context = Context<Self>;
    fn started(&mut self, _: &mut Self::Context) {
    }
}

impl Handler<Event> for ActorDemo {
    type Result = Result<(),()>;
    fn handle(&mut self, event: Event, ctx: &mut Context<Self>) -> Self::Result {
        println!("event {:?}",event);
        match event {
            Event::Update(data) => {
                println!("update ===================================> {}",data);
                self.data=Some(data);
            },
            Event::Notify => {
                if let Some(ref data) = self.data {
                    println!("notify ===========================>{}",data);
                }
            },
        }

        if let Some(notify_handle) = self.notify_handle {
            println!("cacel handle {:?}",notify_handle);
            ctx.cancel_future(notify_handle);
        }

        let notify_handle = ctx.notify_later(Event::Notify, Duration::from_secs(3));
        println!("set notify_handle  {:?}",notify_handle);
        self.notify_handle = Some(notify_handle);
        Ok(())
    }
}

fn main() {
    let system = System::new("test");
    let actor = ActorDemo {
        notify_handle: None,
        data:None,
    };
    let address:SyncAddress<_> = actor.start();

    thread::spawn(move || {
        loop {
            address.send(Event::Update("test".to_owned()));
            sleep(Duration::from_secs(10000));
        }
    });

    
    system.run();

}

~~~

### CODE REVIEW

**Comment by fafhrd91** [comment]
thanks for PR. 

I think better would be remove items from vec only inside poll.

**Comment by woodgear** [comment]
What you mean about that? refactor the implement of cacel_future?

**Comment by fafhrd91** [comment]
I pushed fix in b651491

**Comment by woodgear** [comment]
that cool

**Comment by woodgear** [comment]
when will you make a release? i need this patch.
or i could use git repo

**Comment by fafhrd91** [comment]
0.4.2 is published

**Pull request closed without merging**
