### PR TITLE
Unify MessageResponse impls

### PR DESCRIPTION
**Pull request by semtexzv**
## PR Type

Refactor

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Some code which had left Futures old code, which used separate `Item` and `Error` parameters.

### CODE REVIEW

**Review by robjtede — COMMENTED** [review]
definitely a fan of the single item type

**Review by popzxc — APPROVED** [review]
LGTM. This is a breaking change though, right?

**Comment by semtexzv** [comment]
Yep, a breaking change, but seems long overdue to fix this.

**Review by JohnTitor — APPROVED** [review]
Great refactoring to me! We have #443 in the queue so I'd be welcome this breaking change anyway.

**Pull request merged**
