### PR TITLE
Update to smallvec 1.0

### PR DESCRIPTION
**Pull request by mbrubeck**
See https://github.com/servo/rust-smallvec/releases/tag/v1.0.0 for release notes.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you also update CHANGES.md?

**Comment by leizzer** [comment]
also update your branch please

**Comment by leizzer** [comment]
sorry... misclicked

**Comment by mbrubeck** [comment]
Rebased and updated CHANGES.md.

**Comment by JohnTitor** [comment]
Uhmm, it seems a spurious error on AppVeyor. The previous build succeeded so I think it's okay to merge.

**Pull request merged**
