### PR TITLE
Add `futures::{future, Stream}` to actix::prelude::*

### PR DESCRIPTION
**Pull request by rivertam**
Changed a few tests to reflect/test to make sure compilation still works as expected.

### CODE REVIEW

**Comment by fafhrd91** [comment]
you should be able to merge yourself

**Comment by rivertam** [comment]
@fafhrd91 I am but having reviews is important regardless. Sorry if it was inconvenient.

**Comment by DoumanAsh** [comment]
@rivertam no I think he means if you get approve, you can merge yourself

**Comment by rivertam** [comment]
@DoumanAsh Got it

**Pull request merged**
