### PR TITLE
API Extensions for WeakAddr and WeakRecipient

### PR DESCRIPTION
**Pull request by geo-ant**
## PR Type
Feature

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview
Both `WeakAddr` and `WeakRecipient` now offer a `connected` associated function with the same behavior as their strong counterparts. Furthermore a conversion trait `From<Addr<A>>` for `WeakAddr<A>` was added so that the conversions between weak / strong addresses and weak / strong recipients now all just work.

**(Unlikely) Breaking Change** the `WeakSender` trait was extended by a `connected` associated function. It is unlikely that downstream crates implement this trait themselves, so this will probably not break any code.

### CODE REVIEW

**Comment by geo-ant** [comment]
After I merged the most recent actix/master, the CI now fails on Mac. It seems it is caused by a doc test failing, but I have no clue why. Can someone help?

**Comment by geo-ant** [comment]
hi, the mac CI randomly fails or succeeds after new pushes. Can someone help or tell me what I am missing?

**Comment by geo-ant** [comment]
Hi, the tests seem to pass. Just commenting to ask if there is more I can do to make this feature attractive to merge.

**Comment by geo-ant** [comment]
anyone?

**Comment by Sytten** [comment]
Random failing tests usually means a test is fleaky, will try to do a review

**Comment by geo-ant** [comment]
hi all, I was wondering if there is something I can do to make progress on the PR.

Kind regards
Geo

**Comment by robjtede** [comment]
Despite the low likelihood of downstream implementing WeakSender, I would still want to stick to semver and bump the version to 0.14. Wondering whether sealing this trait (and others?) is a good idea so we can safely make these kinds of changes in future.

Plus, there's some chores to do with actix-web-actors to better support ranges of actix versions.

**Comment by geo-ant** [comment]
Hey, just checking in to see what I can do to get this merged

**Pull request closed without merging**
