### PR TITLE
Add run_until_complete to run single future

### PR DESCRIPTION
**Pull request by DoumanAsh**
I'd like to return option to run single future without a need for manual stopping

### CODE REVIEW

**Comment by fafhrd91** [comment]
tokio runtime provides [block_on](https://docs.rs/tokio/0.1.7/tokio/runtime/struct.Runtime.html#method.block_on)

**Comment by fafhrd91** [comment]
I mean, let’s use block_on instead of combinator

**Comment by fafhrd91** [comment]
@DoumanAsh but what is the point then for `run_until_completed`? you can use just block_on directly.

btw should we use `block_on` name for consistency?

**Comment by DoumanAsh** [comment]
@fafhrd91 Since Actix wraps tokio user should not have need to be exposed to settings of tokio-runtime as actix should choose optimal configuration of runtime for him.

While I know that tokio will be started automatically too, but its defaults are different of these Actix uses.
So I think we should continue to take care of it for user.

If you agree I can rename method to `block_on`

**Comment by fafhrd91** [comment]
I think if we implement this function, runtime should have system. Otherwise it is just too similar to tokio block_on

**Comment by DoumanAsh** [comment]
If we going this way, then I suspect we may not be able to return value of future so signature will require `Future<Item=(), Error=()>` are you ok with that?

I'll look into it more detailed later on

**Comment by fafhrd91** [comment]
Why? We should just use SystemRunner, then we can use same runtime, it contains system arbiter

**Comment by DoumanAsh** [comment]
If we are going to start system, then user will have a way to stop it.
Which means we should decide whether we allow pre-mature end of future or not.
If we allow it then we cannot always return result.
If we do not allow, then I do not see much point in creating system at all.

I guess as you said we might suggest user to use `tokio::Runtimer.block_on` in this case

**Comment by fafhrd91** [comment]
let's do the same as `run` method, just let wait future instead of stop

**Comment by fafhrd91** [comment]
i restored old run_until_complete method

**Comment by DoumanAsh** [comment]
Oh I see thank you

**Pull request closed without merging**
